[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
sqlx = { version = "0.8.1", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
